# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy Project
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install nodejs 
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci 
            - name: Run Test
              run: npm test 
    deployee:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Get code
            uses: actions/checkout@v4
          - name: Install nodejs 
            uses: actions/setup-node@v3
            with:
              node-version: 18
          - name: Install Dependencies
            run: npm ci
          - name: Build Project 
            run: npm run build
          - name: Build Project 
            run: echo "Dploying"

 



        

      

  

